---
- name: Install Docker
  yum:
    name: docker
    state: present
    update_cache: yes

- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: true

- name: Add Kubernetes repository
  copy:
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el9-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install Kubernetes components
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Initialize Kubernetes cluster on master
  command: kubeadm init --apiserver-advertise-address=<master_ip> --pod-network-cidr=10.244.0.0/16
  when: inventory_hostname == "master"

- name: Set up kubeconfig for user on master
  command: "{{ item }}"
  args:
    creates: "{{ item.split(' ')[2].split('=')[1] }}"
  with_items:
    - mkdir -p $HOME/.kube
    - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - chown $(id -u):$(id -g) $HOME/.kube/config
  when: inventory_hostname == "master"

- name: Deploy Flannel network plugin on master
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  args:
    creates: /etc/kubernetes/kube-flannel.yml
  when: inventory_hostname == "master"

- name: Get join command from master
  command: kubeadm token create --print-join-command
  register: join_command
  when: inventory_hostname == "master"

- set_fact:
    join_command: "{{ join_command.stdout }}"
  when: inventory_hostname == "master"
